### ISSUE TITLE
Generic model?

### ISSUE THREAD

**Issue by forresti** [pratyushasharma/laser#20]
Thanks for publishing this excellent work. If I understand correctly, you run LASER intervention separately for each evaluation task.

Would it be possible to make one LASER model that is generic to all tasks? My goal is to compress LLAMA-v2-7B to be smaller, for executing faster on mobile devices.

Also, is it correct that you just apply LASER to one layer of the model? I was wondering, did you try applying it to most of the layers?

**Comment by dkmisra** [comment]
That is correct. We do pick LASER hyperparameters for each task and this is important for seeing the huge gains we report. There is an alternate method called [LaserRMT](https://github.com/cognitivecomputations/laserRMT) that is not from us, which provides a different task-agnostic way to select hyperparameters. I haven't tried it myself but the authors have reported some results.

The simplest way to try LASER across a range of tasks, is to compute a meta-score on a task like AGIEval, and then use it to select the hyperparameter. I am optimistic that we will still see gains across a range of tasks since we find that typically the gains all come from doing intervention in the later MLP layers, and so the optimal hyperparameters tend to have some pattern. The gains might be more modest, compared to only focusing on a single task though.

For most experiments in our paper, we apply LASER to a single layer, or as we say, that is a single LASER intervention. We have an experiment on GPTJ+CounterFact where we composed multiple LASER interventions. See the paragraph `Composing reductions across layers` in the [paper](https://arxiv.org/pdf/2312.13558.pdf). @pratyushasharma has released a script [here](https://github.com/pratyushasharma/laser/blob/main/scripts/laser_compose.py) with details for this experiment, and the upcoming refactoring will support composing LASER in a proper generalizable way.

**Comment by dkmisra** [comment]
Related to #19

**Comment by forresti** [comment]
Thanks so much!!!
