### ISSUE TITLE
How to reproduce Figure 5 analysis in this paper?

### ISSUE THREAD

**Issue by sanyalsunny111** [pratyushasharma/laser#26]
Very cool work. I have curious how to reproduce the figure 5 assessment provided in this paper.

**Comment by dkmisra** [comment]
Hi @sanyalsunny111 . We didnt release code for reproducing that Figure 5 but it should be straightforward to do so. You need to do SVD on GPT-J's weight matrix and then either retain the top-k components like LASER does or the bottom-k components. You then pass a few examples through the model and generate the response.

You should be able to use the codebase except for:
1. you need to provide a list of examples unless you want to pass the entire Counterfact dataset
2. we dont provide code for bottom-k component but you can do that by taking SVD using `torch.svd` and then taking the bottom instead of top components.

**Comment by sanyalsunny111** [comment]
I see thank you for responding. What is the k value considered in this work seems super important towards this analysis.

**Comment by dkmisra** [comment]
Hi @sanyalsunny111 , apologies for the late response and your reading is correct. The choice of hyperparameters is very important. That said, there are now several follow-ups to LASER from other groups that remove some of these restrictions although I haven't compared vanilla LASER with these approaches. E.g.,

- **LASER-RMT:** https://github.com/cognitivecomputations/laserRMT. They do task-agnostic rank reduction

You may also enjoy reading this paper that fine-tunes singular values using backprop: https://arxiv.org/abs/2405.15877

**Comment by sanyalsunny111** [comment]
Thanks @dkmisra.
