### ISSUE TITLE
Where to Get the Dataset

### ISSUE THREAD

**Issue by fakerybakery** [pratyushasharma/laser#5]
Hi,
Thank you so much for making this project! I see that there's a CLI argument for `dataset_file`, do you know what I should point it to for the counterfact method?
Thank you!

**Comment by dkmisra** [comment]
The paper that introduced is this: https://arxiv.org/pdf/2202.05262.pdf and the dataset for which is here: https://rome.baulab.info/data/dsets/counterfact.json. 

However, I processed this dataset a bit so that the file that you refer to, contains a list of (question, answer) pairs. There are 66,000 (roughly) such datapoints which come from approx. 22,000 datapoints and their 3 paraphrases. I need to check if I am allowed to share the dataset that I processed, otherwise, you should be able to download the above json and extract the list I mentioned.

**Comment by fakerybakery** [comment]
Thank you! Might it be possible to provide the code you used to filter the dataset?

**Comment by Yu-Yuqing** [comment]
Thanks a lot!  Could you provide the processed counterfact dataset you mentioned?

**Comment by dkmisra** [comment]
I will upload a short script to create that dataset given the Bau et al. dataset [https://rome.baulab.info/data/dsets/counterfact.json](https://rome.baulab.info/data/dsets/counterfact.json) tomorrow EOD EST.  I think that is most fair to Bau et al.

**Comment by dkmisra** [comment]
@fakerybakery and @Yu-Yuqing , the script to download the dataset is now available [https://github.com/pratyushasharma/laser/blob/main/scripts/get_counterfact.py](https://github.com/pratyushasharma/laser/blob/main/scripts/get_counterfact.py). 

I checked the dataset created by this script against the dataset that we used and it matched 100%. I am closing this issue. If there is an issue, please reopen it.
